// components/Footer.tsx
'use client';

import { useState } from 'react'
import Modal from '@/components/Modal'
import ThemePicker from "./ThemePicker";
import PaletteIcon from '@/components/icons/Palette'
import GithubIcon from '@/components/icons/Github'
import Link from 'next/link'

export default function Footer() {
  const [isModalOpen, setIsModalOpen] = useState(false)

  return (
    <footer className="flex gap-2 justify-center items-center col-start-[content-start] row-start-[footer-start]">
      <div className="icon cursor-pointer" onClick={() => setIsModalOpen(true)}>
        <PaletteIcon fill="var(--main-color)" />
      </div>
      <Link href='https://github.com/lancewilhelm'>
        <GithubIcon fill="var(--main-color)" />
      </Link>
      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)}>
        <ThemePicker />
      </Modal>
    </footer>
  )
}

// app/components/Footer.vue
<script setup>
const showThemePicker = ref(false);
</script>

<template>
    <footer
        class="flex row-start-[content-end] col-start-[content-start] justify-center items-center"
    >
        <div
            class="cursor-pointer flex gap-1 items-center"
            @click="showThemePicker = true"
        >
            <Icon name="fa6-solid:palette" class="text-(--sub-color)" />
            <NuxtLink
                class="flex items-center"
                to="https://github.com/lancewilhelm"
                ><Icon name="simple-icons:github" class="text-(--sub-color)"
            /></NuxtLink>
        </div>
        <ThemePicker v-if="showThemePicker" @close="showThemePicker = false" />
    </footer>
</template>
