// app/components/mdc/BlogImage.vue
<script setup lang="ts">
import { ref } from "vue";

defineProps({
    imagePath: {
        type: String,
        default: "",
    },
    caption: {
        type: String,
        default: "",
    },
    width: {
        type: String,
        default: "",
    },
    height: {
        type: String,
        default: "",
    },
});

const zoomed = ref(false);
</script>

<template>
    <div class="flex flex-col justify-center items-center gap-2 my-[10px]">
        <div
            :style="[
                width ? 'width:' + width : '',
                height ? 'height:' + height : '',
            ]"
            class="max-w-full"
        >
            <img
                :src="imagePath"
                class="w-full cursor-pointer"
                @click="zoomed = true"
            />
        </div>
        <div class="italic max-w-[80vw] text-center">
            <slot name="caption" />
            {{ caption }}
        </div>
        <ImageZoom
            v-if="zoomed"
            :image-path="imagePath"
            @close="zoomed = false"
        />
    </div>
</template>

// components/blogimage.tsx
import Image from 'next/image'

interface ImageProps {
  children: string
  src: string
  width: number
  height: number
  priority?: boolean
}

export default function BlogImage({ children, src, width, height, priority = false }: ImageProps) {
  return (
    <div className="flex flex-col justify-center items-center gap-2">
      {priority ? <Image src={src} alt={children} width={width} height={height} priority /> : <Image src={src} alt={children} width={width} height={height} />}
      <div className="italic text-center">{children}</div>
    </div>
  )
}
